/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c opengl_jsb.ini" on 2013-03-05
* Script version: v0.6
*/
#include "jsapi.h"
#include "jsfriendapi.h"

extern "C" {
    
JSBool JSB_ekDoesObjectExist(JSContext *cx, uint32_t argc, jsval *vp);

}

