/*
* AUTOGENERATED FILE. DO NOT EDIT IT
* Generated by "generate_jsb.py -c opengl_jsb.ini" on 2013-03-05
* Script version: v0.6
*/
#include "js_bindings_config.h"

#include "jsb_opengl_manual.h"

#include "jsfriendapi.h"
//#include "jsb_config.h"
#include "js_bindings_core.h"
#include "js_manual_conversions.h"
#include "cocosjs_manual_conversions.h"
#include "eureekah_manual_functions.h"
#include "cocos2d_specifics.hpp"



JSBool JSB_ekDoesObjectExist(JSContext *cx, uint32_t argc, jsval *vp) {
    jsval *argv = JS_ARGV(cx, vp);
    JSBool ok = JS_TRUE;
	JSB_PRECONDITION2( argc == 1, cx, JS_FALSE, "Invalid number of arguments" );

	cocos2d::CCObject* arg0;
	do {
		if (!argv[0].isObject()) { ok = JS_FALSE; break; }
		js_proxy_t *proxy;
		JSObject *tmpObj = JSVAL_TO_OBJECT(argv[0]);
		proxy = jsb_get_js_proxy(tmpObj);
		arg0 = (cocos2d::CCObject*)(proxy ? proxy->ptr : NULL);
		if (arg0) {
			JS_SET_RVAL(cx, vp, JSVAL_TRUE);
			return JS_TRUE;
		}		
	} while (0);

	JS_SET_RVAL(cx, vp, JSVAL_FALSE);
	return JS_TRUE;

}

